[tools]
just = "latest"
"aqua:nextest-rs/nextest/cargo-nextest" = "latest"
rust = { version = "nightly-2026-08-27", components = ["rustfmt", "rust-src", "clippy", "rust-analyzer"] }
tombi = "latest"

[env]
RUST_BACKTRACE = "1"

[settings]
lockfile = false
